# Inference Configuration
model:
  # Model type
  model_type: "virtual"  # "virtual", "twobody", "explicit-water"

  # Node dimensions
  protein_node_dims:
    scalar: 26
    vector: 3

  virtual_node_dims:
    scalar: 26
    vector: 3

  ligand_node_dims:
    scalar: 46
    vector: 0

  # Edge dimensions
  protein_edge_dims:
    scalar: 41
    vector: 1

  ligand_edge_dims:
    scalar: 9
    vector: 0

  # Hidden dimensions
  hidden_dims:
    protein_scalar: 196
    protein_vector: 16
    virtual_scalar: 196
    virtual_vector: 3
    ligand_scalar: 196
    ligand_vector: 0

  # Architecture parameters
  num_gvp_layers: 4
  dropout: 0.3
  interaction_mode: "hierarchical"

  # Structure prediction
  structure_prediction:
    enabled: true
    model_type: "egnn"
    loss_weight: 0.5
    loss_params:
      loss_type: "mse"
      ligand_weight: 1.0
      sidechain_weight: 1.0
      use_distance_loss: true
      ligand_distance_weight: 0.1
      sidechain_distance_weight: 0.5
      distance_loss_type: "mse"
      distance_cutoff: 5.0

  # Loss parameters
  loss_type: "single"  # single: no classification head
  loss_params:
    huber_delta: 1.0

# Loss configuration
loss:
  type: "single"
  affinity_loss:
    beta: 1.0
    extreme_weight: 1.5
    ranking_weight: 0
  scheduling:
    enabled: true
    structure_warmup_epochs: 10
    affinity_warmup_epochs: 20
    structure_max_weight: 1.0
    affinity_max_weight: 2.0

  # Optimizer parameters (not used in inference but kept for compatibility)
  lr: 1e-3
  weight_decay: 0.01

# Training configuration (needed for model config parsing)
training:
  learning_rate: 5e-4
  optimizer:
    weight_decay: 0.01

# Data configuration
data:
  data_path: "data/"  # Root path for PDB/ligand files
  batch_size: 1
  num_workers: 4
  top_k: 30
  crop_size: 30

# Inference specific parameters
inference:
  meta_path: "data/casp16.json"  # Path to test metadata file
  output_path: "results/predictions.json"  # Output file for predictions
  device: "cuda"  # "cuda" or "cpu"
  batch_size: 1  # Override data batch_size for inference
  num_workers: 4  # Override data num_workers for inference
  
  # Optional: save structure predictions if model supports it
  save_structures: false
  structure_output_dir: "results/structures/"