# Model Configuration
model:
  # Model type
  model_type: "virtual"  # "virtual", "twobody", "explicit-water"

  # Node dimensions
  protein_node_dims:
    scalar: 26
    vector: 3

  virtual_node_dims:
    scalar: 26
    vector: 3

  ligand_node_dims:
    scalar: 46
    vector: 0

  # Edge dimensions
  protein_edge_dims:
    scalar: 41
    vector: 1

  ligand_edge_dims:
    scalar: 9
    vector: 0

  # Hidden dimensions
  hidden_dims:
    protein_scalar: 196
    protein_vector: 16
    virtual_scalar: 196
    virtual_vector: 3
    ligand_scalar: 196
    ligand_vector: 3

  # Model architecture
  num_gvp_layers: 3
  dropout: 0.1
  interaction_mode: "hierarchical"  # "hierarchical" or "parallel"

  # Structure prediction
  structure_prediction:
    enabled: false
    model_type: "egnn"  # "mlp" or "egnn"
    loss_weight: 0.3
    loss_params:
      loss_type: "mse"
      ligand_weight: 1.0
      sidechain_weight: 1.0
      use_distance_loss: true
      ligand_distance_weight: 0.3
      sidechain_distance_weight: 0.1
      distance_loss_type: "mse"
      distance_cutoff: 5.0

# Loss configuration
loss:
  type: "single"  # "single" or "multitask"

  # Affinity loss parameters
  affinity_loss:
    beta: 1.0
    extreme_weight: 1.5
    ranking_weight: 0.5

  # Multitask loss parameters (when loss.type = "multitask")
  multitask_loss:
    thresholds: [4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0]
    regression_weight: 0.75
    category_penalty_weight: 0.15
    extreme_penalty_weight: 0.0
    pearson_penalty_weight: 0.1
    relative_error_weight: 0.1
    extreme_boost_low: 1.3
    extreme_boost_high: 1.4

  # Loss scheduling
  scheduling:
    enabled: true
    structure_warmup_epochs: 15
    affinity_warmup_epochs: 25
    structure_max_weight: 1.0
    affinity_max_weight: 1.0

# Training configuration
training:
  learning_rate: 1e-3
  seed: 42
  max_epochs: 1000
  patience: 10
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"

  # Optimizer
  optimizer:
    type: "adamw"
    weight_decay: 0.01

    # Different learning rates for different components
    lr_multipliers:
      protein_virtual_encoder: 1.0
      ligand_encoder: 1.0
      regressor: 1.0
      structure_predictor: 1.0
      other_params: 1.0

  # Scheduler
  scheduler:
    type: "reduce_lr_on_plateau"
    mode: "min"
    factor: 0.5
    patience: 10
    min_lr: 1e-6
    monitor: "val_loss"

# Data configuration
data:
  data_path: "data/"
  train_data_path: "data/train.json"
  valid_data_path: "data/val.json"
  test_data_path: "data/casp16.json"
  batch_size: 64
  num_workers: 4
  top_k: 30
  crop_size: 30

# Logging and checkpointing
logging:
  project: "protein-ligand-affinity"
  run_name: "gvp_affinity_run"
  wandb_mode: "online"  # "online", "offline", "disabled"
  output_dir: "./outputs"
  log_every_n_steps: 1

  # Checkpointing
  checkpoint:
    dirpath: "checkpoints"
    filename: "model-{epoch:02d}-{val_loss:.4f}"
    monitor: "val_mae"
    mode: "min"
    save_top_k: 3
    save_last: true

  # Early stopping
  early_stopping:
    enabled: false
    monitor: "val_reg_loss"
    mode: "min"
    patience: 10
    min_delta: 0.01
    min_epochs_before_stop: 100

  # Coordinate saving
  coordinate_saving:
    enabled: false
    save_every_n_epochs: 20
    original_mol2_dir: "/home/j2ho/DB/biolip/BioLiP_updated_set/ligand_mol2"
    original_pdb_dir: "/home/j2ho/DB/biolip/BioLiP_updated_set/receptor"
    output_dir: "./predicted_str"
    save_coords_pt: false
    separate_epoch_dirs: false

# Hardware configuration
hardware:
  devices: -1  # -1 for auto-detect, or specify number
  accelerator: "auto"  # "auto", "gpu", "cpu"
  strategy: "ddp_find_unused_parameters_true"
  num_nodes: 1
  accumulate_grad_batches: 1
